# Generated by Django 3.1.7 on 2021-05-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=10, verbose_name='gender')),
                ('birthday', models.DateField(verbose_name='DOB')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('grade', models.CharField(max_length=4, verbose_name='Year of Exp')),
                ('number', models.CharField(max_length=6, verbose_name='Student Num')),
                ('password', models.CharField(max_length=10, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=10, verbose_name='gender')),
                ('birthday', models.DateField(verbose_name='DOB')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('info', models.CharField(help_text='Max 250 words', max_length=255, verbose_name='Bio')),
                ('department_no', models.CharField(max_length=3, verbose_name='course num')),
                ('number', models.CharField(max_length=6, verbose_name='Teacher Num')),
                ('password', models.CharField(max_length=10, verbose_name='Password')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('department_no', 'number'), name='teacher_id'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('grade', 'number'), name='student_id'),
        ),
    ]
